### ISSUE TITLE
av1 dataset

### ISSUE THREAD

**Issue by liuscot** [fudan-zvg/DeMo#15]
Thank you for your outstanding contribution. I see that you have also released the Performance comparison on the agroverse1 dataset. Could you please release the av1_dataset.py of the argoverse1 dataset?

**Comment by Zbozhou** [comment]
I have added the data preprocessing file and the dataset file for the Argoverse 1 dataset.

**Comment by liuscot** [comment]
> I have added the data preprocessing file and the dataset file for the Argoverse 1 dataset.
Thank you for your reply, I wish you a happy life！

**Comment by liuscot** [comment]
Sorry to bother you again, I would like to ask about the detailed configuration when using the argoverse1 dataset for training

**Comment by Zbozhou** [comment]
This is the configuration used before code cleanup. Most settings follow the AV2 dataset. Below are the data and model configurations, which can be adjusted as needed.

```
name: av1-stream
phase: 3frame-20his

target:
  _target_: src.datamodule.av1_datamodule.Av1DataModule

  data_root: 'processed_av1'
  train_batch_size: ${batch_size}
  val_batch_size: ${batch_size}
  test_batch_size: ${batch_size}
  shuffle: True
  num_workers: ${num_workers}
  pin_memory: True
  dataset:
    num_historical_steps: 10
    sequence_origins: [10, 15, 20]
    radius: 50.0
```

```
name: stream
phase: 3grad-ende

target:
  _target_: src.model.trainer_forecast_av1.StreamTrainerAV1
  num_grad_frame: 3
  model:
    type: 'StreamModelForecastAV1'
    embed_dim: 128
    future_steps: 30
    encoder_depth: 4
    num_heads: 8
    mlp_ratio: 4.0
    qkv_bias: False
    drop_path: 0.2
    use_stream_encoder: True
    use_stream_decoder: True
  pretrained_weights: ${pretrained_weights}
  lr: ${lr}
  weight_decay: ${weight_decay}
  epochs: ${epochs}
  warmup_epochs: ${warmup_epochs}
```
